/*
 * This source file was generated by the Gradle 'init' task
 */
package spring.proxy;

import spring.proxy.classes.Man;
import spring.proxy.classes.Person;
import spring.proxy.classes.PersonInvocationHandler;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Proxy;

public class App {

    public static void main(String[] args) {
        Man man = new Man("Samyak" ,"22" ,"Bamora" , "India");

        ClassLoader classLoader = man.getClass().getClassLoader();
        Class [] interfaceLoader = man.getClass().getInterfaces();
        Person person = (Person) Proxy.newProxyInstance(classLoader, interfaceLoader, new PersonInvocationHandler(man) );
        person.sayAge(man.getName());
          person.introduce(man.getName());
    }
}
